export const GET_CURRENCIES_EXCHANGE_RATE_REQUESTED =
  "GET_CURRENCIES_EXCHANGE_RATE_REQUESTED";
export const GET_CURRENCIES_EXCHANGE_RATE_SUCCESS =
  "GET_CURRENCIES_EXCHANGE_RATE_SUCCESS";
export const GET_CURRENCIES_EXCHANGE_RATE_FAIL =
  "GET_CURRENCIES_EXCHANGE_RATE_FAIL";

export const SELECT_ASSET_REQUESTED = "SELECT_ASSET_REQUESTED";
export const SELECT_ASSET_SUCCESS = "SELECT_ASSET_SUCCESS";
export const SELECT_ASSET_FAIL = "SELECT_ASSET_FAIL";

export const SET_ASSETS_AMOUNT_TO_SELL_REQUESTED =
  "SET_ASSETS_AMOUNT_TO_SELL_REQUESTED";
export const SET_ASSETS_AMOUNT_TO_SELL_SUCCESS =
  "SET_ASSETS_AMOUNT_TO_SELL_SUCCESS";
export const SET_ASSETS_AMOUNT_TO_SELL_FAIL = "SET_ASSETS_AMOUNT_TO_SELL_FAIL";

export const SET_CAP_ASSET_REQUESTED = "SET_CAP_ASSET_REQUESTED";
export const SET_CAP_ASSET_SUCCESS = "SET_CAP_ASSET_SUCCESS";
export const SET_CAP_ASSET_FAIL = "SET_CAP_ASSET_FAIL";
